name: AccountingApp
options:
  bundleIdPrefix: com.shawn
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: en
  xcodeVersion: 15.0
settings:
  SWIFT_VERSION: 5.9
targets:
  AccountingApp:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - AccountingApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.shawn.AccountingApp
      INFOPLIST_FILE: AccountingApp/Info.plist
      TARGETED_DEVICE_FAMILY: 1,2
      SWIFT_VERSION: 5.9
      ENABLE_PREVIEWS: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
